#include <ibex/codegen/emitter.hpp>
#include <ibex/ir/node.hpp>

#include <cmath>
#include <cstdint>
#include <sstream>
#include <stdexcept>
#include <string>
#include <string_view>
#include <utility>

namespace ibex::codegen {

namespace {

auto escape_string(const std::string& s) -> std::string {
    std::string out;
    out.reserve(s.size());
    for (char c : s) {
        if (c == '"')
            out += "\\\"";
        else if (c == '\\')
            out += "\\\\";
        else if (c == '\n')
            out += "\\n";
        else if (c == '\r')
            out += "\\r";
        else if (c == '\t')
            out += "\\t";
        else
            out += c;
    }
    return out;
}

auto format_double(double v) -> std::string {
    if (std::isnan(v))
        return "std::numeric_limits<double>::quiet_NaN()";
    if (std::isinf(v))
        return v > 0 ? "std::numeric_limits<double>::infinity()"
                     : "-std::numeric_limits<double>::infinity()";
    // Round-trip precision
    std::ostringstream ss;
    ss.precision(17);
    ss << v;
    std::string s = ss.str();
    // Ensure it looks like a double literal (has . or e)
    if (s.find('.') == std::string::npos && s.find('e') == std::string::npos) {
        s += ".0";
    }
    return s;
}

}  // namespace

// ─── Public ──────────────────────────────────────────────────────────────────

auto Emitter::indent_code(const std::string& code, size_t spaces) -> std::string {
    if (spaces <= 0 || code.empty())
        return code;
    std::string prefix(spaces, ' ');
    std::string result;
    result.reserve(code.size() + (prefix.size() * 16));
    bool at_start = true;
    for (char c : code) {
        if (at_start && c != '\n') {
            result += prefix;
            at_start = false;
        }
        result += c;
        if (c == '\n')
            at_start = true;
    }
    return result;
}

void Emitter::emit(std::ostream& out, const ir::Node& root, const Config& config) {
    out_ = &out;
    tmp_counter_ = 0;
    cached_vars_.clear();

    // Preamble
    if (!config.source_name.empty()) {
        out << "// Generated by ibex compiler\n";
        out << "// Source: " << config.source_name << "\n";
        out << "\n";
    } else {
        out << "// Generated by ibex compiler\n\n";
    }

    out << "#include <cstdint>\n";
    out << "#include <ctime>\n";
    if (config.bench_mode)
        out << "#include <chrono>\n#include <cstdio>\n";
    else
        out << "#include <iostream>\n";
    out << "#include <limits>\n";
    out << "#include <optional>\n";
    out << "#include <string>\n";
    out << "#include <variant>\n";
    out << "#include <vector>\n";
    out << "#include <ibex/runtime/ops.hpp>\n";
    out << "#include <ibex/runtime/extern_registry.hpp>\n";

    for (const auto& hdr : config.extern_headers) {
        out << "#include \"" << escape_string(hdr) << "\"\n";
    }

    out << "\n";
    out << "int main() {\n";

    if (!config.scalar_bindings.empty()) {
        out << "    ibex::runtime::ScalarRegistry _ibex_scalars;\n";
        for (const auto& [name, value] : config.scalar_bindings) {
            out << "    _ibex_scalars[\"" << escape_string(name) << "\"] = ";
            std::visit(
                [&](const auto& v) {
                    using V = std::decay_t<decltype(v)>;
                    if constexpr (std::is_same_v<V, std::int64_t>) {
                        out << "std::int64_t{" << v << "}";
                    } else if constexpr (std::is_same_v<V, double>) {
                        out << format_double(v);
                    } else if constexpr (std::is_same_v<V, bool>) {
                        out << (v ? "true" : "false");
                    } else if constexpr (std::is_same_v<V, std::string>) {
                        out << "\"" << escape_string(v) << "\"";
                    } else if constexpr (std::is_same_v<V, Date>) {
                        out << "ibex::Date{std::int32_t{" << v.days << "}}";
                    } else {
                        static_assert(std::is_same_v<V, Timestamp>);
                        out << "ibex::Timestamp{std::int64_t{" << v.nanos << "}}";
                    }
                },
                value);
            out << ";\n";
        }
        out << "    ibex::ops::set_scalars(&_ibex_scalars);\n\n";
    }

    if (config.bench_mode) {
        // Phase 1: emit ExternCall (data loading) nodes into main buffer (setup).
        collect_extern_calls(root);

        // Phase 2: emit the query into a temporary buffer.
        std::ostringstream query_buf;
        auto* saved_out = out_;
        out_ = &query_buf;
        auto result_var = emit_node(root);
        out_ = saved_out;

        // Re-indent query code by 4 extra spaces so it sits inside the loop body.
        std::string query_code = indent_code(query_buf.str(), 4);

        // Warmup loop
        out << "\n    // Warmup\n";
        out << "    for (int _bench_w = 0; _bench_w < " << config.bench_warmup
            << "; ++_bench_w) {\n";
        out << query_code;
        out << "        (void)" << result_var << ";\n";
        out << "    }\n";

        // Timed loop
        out << "\n    // Timed iterations\n";
        out << "    auto _bench_t0 = std::chrono::steady_clock::now();\n";
        out << "    for (int _bench_i = 0; _bench_i < " << config.bench_iters
            << "; ++_bench_i) {\n";
        out << query_code;
        out << "        (void)" << result_var << ";\n";
        out << "    }\n";
        out << "    auto _bench_t1 = std::chrono::steady_clock::now();\n";
        out << "    double _avg_ms = std::chrono::duration<double, std::milli>"
               "(_bench_t1 - _bench_t0).count() / "
            << config.bench_iters << ";\n";
        out << "    std::fprintf(stderr, \"avg_ms=%.3f\\n\", _avg_ms);\n";
    } else {
        auto result_var = emit_node(root);
        if (config.print_result) {
            out << "    ibex::ops::print(" << result_var << ");\n";
        }
    }

    out << "    return 0;\n";
    out << "}\n";

    out_ = nullptr;
}

void Emitter::collect_extern_calls(const ir::Node& node) {
    if (cached_vars_.contains(&node))
        return;
    if (node.kind() == ir::NodeKind::ExternCall) {
        // NOLINTNEXTLINE(cppcoreguidelines-pro-type-static-cast-downcast)
        const auto& ec = static_cast<const ir::ExternCallNode&>(node);
        auto var = fresh_var();
        *out_ << "    auto " << var << " = " << ec.callee() << "(";
        bool first = true;
        for (const auto& arg : ec.args()) {
            if (!first)
                *out_ << ", ";
            first = false;
            *out_ << emit_raw_expr(arg);
        }
        *out_ << ");\n";
        cached_vars_[&node] = var;
        return;
    }
    for (const auto& child : node.children()) {
        if (!child) {
            throw std::runtime_error("ibex_compile: IR contains a null child node");
        }
        collect_extern_calls(*child);
    }
}

// ─── Private helpers ─────────────────────────────────────────────────────────

auto Emitter::fresh_var() -> std::string {
    return "t" + std::to_string(tmp_counter_++);
}

auto Emitter::emit_node(const ir::Node& node) -> std::string {
    const auto require_single_child = [](const ir::Node& parent,
                                         std::string_view node_name) -> const ir::Node& {
        if (parent.children().size() != 1 || !parent.children().front()) {
            throw std::runtime_error("ibex_compile: " + std::string(node_name) +
                                     " expects exactly one non-null child");
        }
        return *parent.children().front();
    };

    // NOLINTBEGIN cppcoreguidelines-pro-type-static-cast-downcast
    switch (node.kind()) {
        case ir::NodeKind::Scan: {
            // NOLINTNEXTLINE cppcoreguidelines-pro-type-static-cast-downcast
            const auto& scan = static_cast<const ir::ScanNode&>(node);
            if (scan.source_name() == "__stream_input__" && !stream_scan_var_.empty()) {
                return stream_scan_var_;
            }
            throw std::runtime_error(
                "ibex_compile: ScanNode cannot be emitted — use 'extern fn' to declare data "
                "sources");
        }

        case ir::NodeKind::Filter: {
            const auto& filter = static_cast<const ir::FilterNode&>(node);
            auto child = emit_node(require_single_child(filter, "FilterNode"));
            auto var = fresh_var();
            *out_ << "    auto " << var << " = ibex::ops::filter(" << child << ", "
                  << emit_filter_expr(filter.predicate()) << ");\n";
            return var;
        }

        case ir::NodeKind::Project: {
            const auto& proj = static_cast<const ir::ProjectNode&>(node);
            auto child = emit_node(require_single_child(proj, "ProjectNode"));
            auto var = fresh_var();
            *out_ << "    auto " << var << " = ibex::ops::project(" << child << ", {";
            bool first = true;
            for (const auto& col : proj.columns()) {
                if (!first)
                    *out_ << ", ";
                first = false;
                *out_ << '"' << escape_string(col.name) << '"';
            }
            *out_ << "});\n";
            return var;
        }

        case ir::NodeKind::Distinct: {
            auto child = emit_node(require_single_child(node, "DistinctNode"));
            auto var = fresh_var();
            *out_ << "    auto " << var << " = ibex::ops::distinct(" << child << ");\n";
            return var;
        }

        case ir::NodeKind::Order: {
            const auto& order = static_cast<const ir::OrderNode&>(node);
            auto child = emit_node(require_single_child(order, "OrderNode"));
            auto var = fresh_var();
            *out_ << "    auto " << var << " = ibex::ops::order(" << child << ", {";
            bool first = true;
            for (const auto& key : order.keys()) {
                if (!first)
                    *out_ << ", ";
                first = false;
                *out_ << "ibex::ir::OrderKey{\"" << escape_string(key.name) << "\", "
                      << (key.ascending ? "true" : "false") << "}";
            }
            *out_ << "});\n";
            return var;
        }

        case ir::NodeKind::Head: {
            const auto& head = static_cast<const ir::HeadNode&>(node);
            auto child = emit_node(require_single_child(head, "HeadNode"));
            auto var = fresh_var();
            *out_ << "    auto " << var << " = ibex::ops::head(" << child << ", " << head.count()
                  << ", {";
            bool first = true;
            for (const auto& key : head.group_by()) {
                if (!first)
                    *out_ << ", ";
                first = false;
                *out_ << '"' << escape_string(key.name) << '"';
            }
            *out_ << "});\n";
            return var;
        }

        case ir::NodeKind::Aggregate: {
            const auto& agg = static_cast<const ir::AggregateNode&>(node);
            auto child = emit_node(require_single_child(agg, "AggregateNode"));
            auto var = fresh_var();
            *out_ << "    auto " << var << " = ibex::ops::aggregate(" << child << ",\n";

            // group_by
            *out_ << "        {";
            bool first = true;
            for (const auto& g : agg.group_by()) {
                if (!first)
                    *out_ << ", ";
                first = false;
                *out_ << '"' << escape_string(g.name) << '"';
            }
            *out_ << "},\n";

            // aggregations
            *out_ << "        {";
            first = true;
            for (const auto& a : agg.aggregations()) {
                if (!first)
                    *out_ << ", ";
                first = false;
                *out_ << "ibex::ops::make_agg("
                      << "ibex::ir::AggFunc::" << emit_agg_func(a.func) << ", \""
                      << escape_string(a.column.name) << "\", \"" << escape_string(a.alias)
                      << "\", " << format_double(a.param) << ")";
            }
            *out_ << "});\n";
            return var;
        }

        case ir::NodeKind::Update: {
            const auto& upd = static_cast<const ir::UpdateNode&>(node);
            auto child = emit_node(require_single_child(upd, "UpdateNode"));
            auto var = fresh_var();

            std::vector<std::pair<std::vector<std::string>, std::string>> tuple_sources;
            tuple_sources.reserve(upd.tuple_fields().size());
            for (const auto& tf : upd.tuple_fields()) {
                if (!tf.source) {
                    throw std::runtime_error("ibex_compile: UpdateNode tuple source is null");
                }
                tuple_sources.emplace_back(tf.aliases, emit_node(*tf.source));
            }

            *out_ << "    auto " << var << " = ibex::ops::update(" << child << ", {\n";
            bool first = true;
            for (const auto& f : upd.fields()) {
                if (!first)
                    *out_ << ",\n";
                first = false;
                *out_ << "        ibex::ops::make_field(\"" << escape_string(f.alias) << "\", "
                      << emit_expr(f.expr) << ")";
            }
            *out_ << "\n    }, {";

            bool first_tuple = true;
            for (const auto& tf : tuple_sources) {
                if (!first_tuple)
                    *out_ << ", ";
                first_tuple = false;
                *out_ << "ibex::ops::TupleSource{{";
                bool first_alias = true;
                for (const auto& alias : tf.first) {
                    if (!first_alias)
                        *out_ << ", ";
                    first_alias = false;
                    *out_ << '"' << escape_string(alias) << '"';
                }
                *out_ << "}, " << tf.second << "}";
            }

            *out_ << "}, {";
            bool first_group = true;
            for (const auto& key : upd.group_by()) {
                if (!first_group)
                    *out_ << ", ";
                first_group = false;
                *out_ << '"' << escape_string(key.name) << '"';
            }
            *out_ << "});\n";
            return var;
        }

        case ir::NodeKind::Rename: {
            const auto& ren = static_cast<const ir::RenameNode&>(node);
            auto child = emit_node(require_single_child(ren, "RenameNode"));
            auto var = fresh_var();
            *out_ << "    auto " << var << " = ibex::ops::rename(" << child << ", {";
            bool first = true;
            for (const auto& spec : ren.renames()) {
                if (!first)
                    *out_ << ", ";
                first = false;
                *out_ << "ibex::ir::RenameSpec{\"" << escape_string(spec.new_name) << "\", \""
                      << escape_string(spec.old_name) << "\"}";
            }
            *out_ << "});\n";
            return var;
        }

        case ir::NodeKind::Window: {
            const auto& win = static_cast<const ir::WindowNode&>(node);
            const auto& window_child = require_single_child(win, "WindowNode");
            if (window_child.kind() != ir::NodeKind::Update) {
                throw std::runtime_error("ibex_compile: WindowNode must have an UpdateNode child");
            }
            const auto& upd = static_cast<const ir::UpdateNode&>(window_child);
            if (!upd.tuple_fields().empty() || !upd.group_by().empty()) {
                throw std::runtime_error(
                    "ibex_compile: windowed update with tuple fields or by-clause is not "
                    "supported in the compiled path");
            }
            auto source = emit_node(require_single_child(upd, "UpdateNode (window payload)"));
            auto var = fresh_var();
            *out_ << "    auto " << var << " = ibex::ops::windowed_update(" << source << ",\n";
            *out_ << "        ibex::ir::Duration(" << win.duration().count() << "LL),\n";
            *out_ << "        {";
            bool first = true;
            for (const auto& f : upd.fields()) {
                if (!first)
                    *out_ << ",\n         ";
                first = false;
                *out_ << "ibex::ops::make_field(\"" << escape_string(f.alias) << "\", "
                      << emit_expr(f.expr) << ")";
            }
            *out_ << "});\n";
            return var;
        }

        case ir::NodeKind::Resample: {
            const auto& rs = static_cast<const ir::ResampleNode&>(node);
            auto child = emit_node(require_single_child(rs, "ResampleNode"));
            auto var = fresh_var();
            *out_ << "    auto " << var << " = ibex::ops::resample(" << child << ",\n";

            // duration (nanoseconds count)
            *out_ << "        ibex::ir::Duration(" << rs.duration().count() << "LL),\n";

            // group_by
            *out_ << "        {";
            bool first = true;
            for (const auto& g : rs.group_by()) {
                if (!first)
                    *out_ << ", ";
                first = false;
                *out_ << '"' << escape_string(g.name) << '"';
            }
            *out_ << "},\n";

            // aggregations
            *out_ << "        {";
            first = true;
            for (const auto& a : rs.aggregations()) {
                if (!first)
                    *out_ << ", ";
                first = false;
                *out_ << "ibex::ops::make_agg("
                      << "ibex::ir::AggFunc::" << emit_agg_func(a.func) << ", \""
                      << escape_string(a.column.name) << "\", \"" << escape_string(a.alias)
                      << "\", " << format_double(a.param) << ")";
            }
            *out_ << "});\n";
            return var;
        }

        case ir::NodeKind::AsTimeframe: {
            const auto& atf = static_cast<const ir::AsTimeframeNode&>(node);
            auto child = emit_node(require_single_child(atf, "AsTimeframeNode"));
            auto var = fresh_var();
            *out_ << "    auto " << var << " = ibex::ops::as_timeframe(" << child << ", \""
                  << escape_string(atf.column()) << "\");\n";
            return var;
        }

        case ir::NodeKind::ExternCall: {
            // In bench mode ExternCall nodes were pre-emitted; reuse the var.
            if (auto it = cached_vars_.find(&node); it != cached_vars_.end())
                return it->second;
            const auto& ec = static_cast<const ir::ExternCallNode&>(node);
            auto var = fresh_var();
            *out_ << "    auto " << var << " = " << ec.callee() << "(";
            bool first = true;
            for (const auto& arg : ec.args()) {
                if (!first)
                    *out_ << ", ";
                first = false;
                *out_ << emit_raw_expr(arg);
            }
            *out_ << ");\n";
            return var;
        }

        case ir::NodeKind::Join: {
            const auto& join = static_cast<const ir::JoinNode&>(node);
            if (join.children().size() != 2) {
                throw std::runtime_error("ibex_compile: JoinNode expects two children");
            }
            if (!join.children()[0] || !join.children()[1]) {
                throw std::runtime_error("ibex_compile: JoinNode children must be non-null");
            }
            auto left = emit_node(*join.children()[0]);
            auto right = emit_node(*join.children()[1]);
            auto var = fresh_var();
            const char* fn = nullptr;
            const char* kind = nullptr;
            switch (join.kind()) {
                case ir::JoinKind::Inner:
                    fn = "inner_join";
                    kind = "Inner";
                    break;
                case ir::JoinKind::Left:
                    fn = "left_join";
                    kind = "Left";
                    break;
                case ir::JoinKind::Right:
                    fn = "right_join";
                    kind = "Right";
                    break;
                case ir::JoinKind::Outer:
                    fn = "outer_join";
                    kind = "Outer";
                    break;
                case ir::JoinKind::Semi:
                    fn = "semi_join";
                    kind = "Semi";
                    break;
                case ir::JoinKind::Anti:
                    fn = "anti_join";
                    kind = "Anti";
                    break;
                case ir::JoinKind::Cross:
                    fn = "cross_join";
                    kind = "Cross";
                    break;
                case ir::JoinKind::Asof:
                    fn = "asof_join";
                    kind = "Asof";
                    break;
            }
            if (join.predicate().has_value()) {
                *out_ << "    auto " << var << " = ibex::ops::join_with_predicate(" << left << ", "
                      << right << ", ibex::ir::JoinKind::" << kind << ", {";
                bool first = true;
                for (const auto& key : join.keys()) {
                    if (!first)
                        *out_ << ", ";
                    first = false;
                    *out_ << '"' << escape_string(key) << '"';
                }
                *out_ << "}, " << emit_filter_expr(**join.predicate()) << ");\n";
                return var;
            }
            *out_ << "    auto " << var << " = ibex::ops::" << fn << "(" << left << ", " << right;
            if (join.kind() != ir::JoinKind::Cross) {
                *out_ << ", {";
                bool first = true;
                for (const auto& key : join.keys()) {
                    if (!first)
                        *out_ << ", ";
                    first = false;
                    *out_ << '"' << escape_string(key) << '"';
                }
                *out_ << "}";
            }
            *out_ << ");\n";
            return var;
        }

        case ir::NodeKind::Melt: {
            const auto& mn = static_cast<const ir::MeltNode&>(node);
            auto child = emit_node(require_single_child(mn, "MeltNode"));
            auto var = fresh_var();
            *out_ << "    auto " << var << " = ibex::ops::melt(" << child << ", {";
            bool first = true;
            for (const auto& col : mn.id_columns()) {
                if (!first)
                    *out_ << ", ";
                first = false;
                *out_ << '"' << escape_string(col) << '"';
            }
            *out_ << "}, {";
            first = true;
            for (const auto& col : mn.measure_columns()) {
                if (!first)
                    *out_ << ", ";
                first = false;
                *out_ << '"' << escape_string(col) << '"';
            }
            *out_ << "});\n";
            return var;
        }

        case ir::NodeKind::Dcast: {
            const auto& dn = static_cast<const ir::DcastNode&>(node);
            auto child = emit_node(require_single_child(dn, "DcastNode"));
            auto var = fresh_var();
            *out_ << "    auto " << var << " = ibex::ops::dcast(" << child << ", \""
                  << escape_string(dn.pivot_column()) << "\", \""
                  << escape_string(dn.value_column()) << "\", {";
            bool first = true;
            for (const auto& key : dn.row_keys()) {
                if (!first)
                    *out_ << ", ";
                first = false;
                *out_ << '"' << escape_string(key) << '"';
            }
            *out_ << "});\n";
            return var;
        }

        case ir::NodeKind::Cov: {
            auto child = emit_node(require_single_child(node, "CovNode"));
            auto var = fresh_var();
            *out_ << "    auto " << var << " = ibex::ops::cov(" << child << ");\n";
            return var;
        }

        case ir::NodeKind::Corr: {
            auto child = emit_node(require_single_child(node, "CorrNode"));
            auto var = fresh_var();
            *out_ << "    auto " << var << " = ibex::ops::corr(" << child << ");\n";
            return var;
        }

        case ir::NodeKind::Transpose: {
            auto child = emit_node(require_single_child(node, "TransposeNode"));
            auto var = fresh_var();
            *out_ << "    auto " << var << " = ibex::ops::transpose(" << child << ");\n";
            return var;
        }

        case ir::NodeKind::Matmul: {
            if (node.children().size() != 2) {
                throw std::runtime_error("MatmulNode expects exactly two children");
            }
            auto left = emit_node(*node.children()[0]);
            auto right = emit_node(*node.children()[1]);
            auto var = fresh_var();
            *out_ << "    auto " << var << " = ibex::ops::matmul(" << left << ", " << right
                  << ");\n";
            return var;
        }

        case ir::NodeKind::Model: {
            // Model fitting is not yet supported in codegen — it requires the full
            // runtime interpreter.  Emit a placeholder that errors at compile time.
            throw std::runtime_error("model clause is not yet supported in compiled mode");
        }

        case ir::NodeKind::Construct: {
            const auto& cn = static_cast<const ir::ConstructNode&>(node);
            auto var = fresh_var();
            *out_ << "    ibex::runtime::Table " << var << ";\n";
            for (const auto& col : cn.columns()) {
                if (col.expr_node) {
                    // Expression column: emit the sub-node then extract the column.
                    auto sub_var = emit_node(*col.expr_node);
                    auto cname = escape_string(col.name);
                    *out_ << "    {\n";
                    *out_ << "        auto& __sub = " << sub_var << ";\n";
                    *out_ << "        if (__sub.columns.size() == 1) {\n";
                    *out_ << "            auto __entry = __sub.columns[0];\n";
                    *out_ << "            __entry.name = \"" << cname << "\";\n";
                    *out_ << "            " << var << ".index[\"" << cname << "\"] = " << var
                          << ".columns.size();\n";
                    *out_ << "            " << var << ".columns.push_back(std::move(__entry));\n";
                    *out_ << "        } else {\n";
                    *out_ << "            auto __it = __sub.index.find(\"" << cname << "\");\n";
                    *out_ << "            if (__it == __sub.index.end())\n";
                    *out_
                        << "                throw std::runtime_error(\"Table constructor: column '"
                        << cname << "' not found in expression result\");\n";
                    *out_ << "            auto __entry = __sub.columns[__it->second];\n";
                    *out_ << "            __entry.name = \"" << cname << "\";\n";
                    *out_ << "            " << var << ".index[\"" << cname << "\"] = " << var
                          << ".columns.size();\n";
                    *out_ << "            " << var << ".columns.push_back(std::move(__entry));\n";
                    *out_ << "        }\n";
                    *out_ << "    }\n";
                    continue;
                }
                if (col.elements.empty()) {
                    *out_ << "    " << var << ".add_column(\"" << escape_string(col.name)
                          << "\", ibex::Column<std::int64_t>{});\n";
                    continue;
                }
                // Determine column type from first element and emit the add_column call.
                std::visit(
                    [&](const auto& first_val) {
                        using T = std::decay_t<decltype(first_val)>;
                        std::string type_str;
                        if constexpr (std::is_same_v<T, std::int64_t>) {
                            type_str = "std::int64_t";
                        } else if constexpr (std::is_same_v<T, double>) {
                            type_str = "double";
                        } else if constexpr (std::is_same_v<T, bool>) {
                            type_str = "bool";
                        } else if constexpr (std::is_same_v<T, std::string>) {
                            type_str = "std::string";
                        } else if constexpr (std::is_same_v<T, Date>) {
                            type_str = "ibex::Date";
                        } else {
                            static_assert(std::is_same_v<T, Timestamp>);
                            type_str = "ibex::Timestamp";
                        }
                        *out_ << "    " << var << ".add_column(\"" << escape_string(col.name)
                              << "\", ibex::Column<" << type_str << ">{";
                        bool first = true;
                        for (const auto& lit : col.elements) {
                            if (!first)
                                *out_ << ", ";
                            first = false;
                            std::visit(
                                [&](const auto& v) {
                                    using V = std::decay_t<decltype(v)>;
                                    if constexpr (std::is_same_v<V, std::int64_t>) {
                                        *out_ << "std::int64_t{" << std::to_string(v) << "}";
                                    } else if constexpr (std::is_same_v<V, double>) {
                                        *out_ << format_double(v);
                                    } else if constexpr (std::is_same_v<V, bool>) {
                                        *out_ << (v ? "true" : "false");
                                    } else if constexpr (std::is_same_v<V, std::string>) {
                                        *out_ << '"' << escape_string(v) << '"';
                                    } else if constexpr (std::is_same_v<V, Date>) {
                                        *out_ << "ibex::Date{std::int32_t{"
                                              << std::to_string(v.days) << "}}";
                                    } else {
                                        static_assert(std::is_same_v<V, Timestamp>);
                                        *out_ << "ibex::Timestamp{std::int64_t{"
                                              << std::to_string(v.nanos) << "}}";
                                    }
                                },
                                lit.value);
                        }
                        *out_ << "});\n";
                    },
                    col.elements[0].value);
            }
            return var;
        }

        case ir::NodeKind::Stream: {
            // NOLINTNEXTLINE cppcoreguidelines-pro-type-static-cast-downcast
            const auto& sn = static_cast<const ir::StreamNode&>(node);
            auto var = fresh_var();

            // ── Emit the transform into a temporary buffer ────────────────────
            // The transform IR starts with ScanNode("__stream_input__").
            // We substitute it with the lambda parameter "_ibex_sbuf".
            const std::string sbuf = "_ibex_sbuf";
            std::ostringstream transform_buf;
            auto* saved_out = out_;
            out_ = &transform_buf;
            stream_scan_var_ = sbuf;
            auto transform_var = emit_node(sn.transform_ir());
            stream_scan_var_.clear();
            out_ = saved_out;

            // ── Emit the "flush" lambda: transform buffer → sink ──────────────
            const std::string emit_fn = "_emit_fn_" + var;
            *out_ << "    auto " << emit_fn << " = [&](const ibex::runtime::Table& " << sbuf
                  << ") {\n";
            *out_ << "        if (" << sbuf << ".rows() == 0) return;\n";
            *out_ << indent_code(transform_buf.str(), 4);
            *out_ << "        " << sn.sink_callee() << "(" << transform_var;
            for (const auto& arg : sn.sink_args()) {
                *out_ << ", " << emit_raw_expr(arg);
            }
            *out_ << ");\n";
            *out_ << "    };\n\n";

            // ── Emit the source-normalisation lambda ──────────────────────────
            // Source may return Table (e.g. udp_recv) or ExternValue (e.g. ws_recv).
            // We normalise both to ExternValue so the event loop is uniform.
            const std::string call_src = "_call_src_" + var;
            *out_ << "    auto " << call_src << " = [&]() -> ibex::runtime::ExternValue {\n";
            *out_ << "        auto _r = " << sn.source_callee() << "(";
            {
                bool first = true;
                for (const auto& arg : sn.source_args()) {
                    if (!first)
                        *out_ << ", ";
                    first = false;
                    *out_ << emit_raw_expr(arg);
                }
            }
            *out_ << ");\n";
            *out_ << "        if constexpr (std::is_same_v<decltype(_r), "
                     "ibex::runtime::ExternValue>) {\n";
            *out_ << "            return _r;\n";
            *out_ << "        } else {\n";
            *out_ << "            return ibex::runtime::ExternValue{std::move(_r)};\n";
            *out_ << "        }\n";
            *out_ << "    };\n\n";

            const std::string buf = "_buf_" + var;
            *out_ << "    ibex::runtime::Table " << buf << ";\n";

            if (sn.stream_kind() == ir::StreamKind::TimeBucket) {
                const auto bucket_ns = static_cast<std::int64_t>(sn.bucket_duration().count());
                *out_ << "    std::int64_t _bopen_" << var << " = -1;\n";
                *out_ << "    std::int64_t _bwall_" << var << " = -1;\n";
                *out_ << "    const std::int64_t _bns_" << var << " = std::int64_t{" << bucket_ns
                      << "LL};\n\n";

                *out_ << "    while (true) {\n";
                *out_ << "        auto _src_" << var << " = " << call_src << "();\n";
                *out_ << "        const bool _tout_" << var
                      << " = std::holds_alternative<ibex::runtime::StreamTimeout>(_src_" << var
                      << ");\n";
                *out_ << "        if (!_tout_" << var << ") {\n";
                *out_ << "            if (std::get<ibex::runtime::Table>(_src_" << var
                      << ").rows() == 0) break;\n";
                *out_ << "        }\n";

                // Wall-clock flush
                *out_ << "        {\n";
                *out_ << "            struct timespec _tp_" << var << "{};\n";
                *out_ << "            clock_gettime(CLOCK_REALTIME, &_tp_" << var << ");\n";
                *out_ << "            std::int64_t _wall_" << var << " = std::int64_t(_tp_" << var
                      << ".tv_sec) * 1'000'000'000LL\n";
                *out_ << "                       + std::int64_t(_tp_" << var << ".tv_nsec);\n";
                *out_ << "            if (_bopen_" << var << " >= 0 && " << buf
                      << ".rows() > 0 &&\n";
                *out_ << "                _wall_" << var << " - _bwall_" << var << " >= _bns_"
                      << var << ") {\n";
                *out_ << "                " << emit_fn << "(" << buf << ");\n";
                *out_ << "                " << buf << " = ibex::runtime::Table{};\n";
                *out_ << "                _bopen_" << var << " = -1; _bwall_" << var << " = -1;\n";
                *out_ << "            }\n";

                // Row-by-row bucket detection
                *out_ << "            if (!_tout_" << var << ") {\n";
                *out_ << "                const auto& _batch_" << var
                      << " = std::get<ibex::runtime::Table>(_src_" << var << ");\n";
                *out_ << "                for (std::size_t _ri_" << var << " = 0; _ri_" << var
                      << " < _batch_" << var << ".rows(); ++_ri_" << var << ") {\n";
                *out_ << "                    auto _rts_" << var
                      << " = ibex::ops::stream_get_ts_ns(_batch_" << var << ", _ri_" << var
                      << ");\n";
                *out_ << "                    const std::int64_t _rbk_" << var << " = _rts_" << var
                      << " ? ((*_rts_" << var << " / _bns_" << var << ") * _bns_" << var
                      << ") : -1;\n";
                *out_ << "                    if (_bopen_" << var << " >= 0 && _rbk_" << var
                      << " >= 0 && _rbk_" << var << " > _bopen_" << var << ") {\n";
                *out_ << "                        " << emit_fn << "(" << buf << ");\n";
                *out_ << "                        " << buf << " = ibex::runtime::Table{};\n";
                *out_ << "                    }\n";
                *out_ << "                    if (_rbk_" << var << " >= 0) {\n";
                *out_ << "                        if (_rbk_" << var << " != _bopen_" << var
                      << ") _bwall_" << var << " = _wall_" << var << ";\n";
                *out_ << "                        _bopen_" << var << " = _rbk_" << var << ";\n";
                *out_ << "                    }\n";
                *out_ << "                    ibex::ops::stream_append_row(" << buf << ", _batch_"
                      << var << ", _ri_" << var << ");\n";
                *out_ << "                }\n";
                *out_ << "            }\n";
                *out_ << "        }\n";
                *out_ << "    }\n";
                *out_ << "    if (" << buf << ".rows() > 0) " << emit_fn << "(" << buf << ");\n";
            } else {
                // PerRow: append entire batch then run transform on accumulated buffer.
                *out_ << "    while (true) {\n";
                *out_ << "        auto _src_" << var << " = " << call_src << "();\n";
                *out_ << "        if (std::holds_alternative<ibex::runtime::StreamTimeout>(_src_"
                      << var << ")) continue;\n";
                *out_ << "        const auto& _batch_" << var
                      << " = std::get<ibex::runtime::Table>(_src_" << var << ");\n";
                *out_ << "        if (_batch_" << var << ".rows() == 0) break;\n";
                *out_ << "        for (std::size_t _ri_" << var << " = 0; _ri_" << var
                      << " < _batch_" << var << ".rows(); ++_ri_" << var << ") {\n";
                *out_ << "            ibex::ops::stream_append_row(" << buf << ", _batch_" << var
                      << ", _ri_" << var << ");\n";
                *out_ << "        }\n";
                *out_ << "        " << emit_fn << "(" << buf << ");\n";
                *out_ << "    }\n";
            }

            *out_ << "    ibex::runtime::Table " << var << ";\n";
            return var;
        }
        case ir::NodeKind::Program: {
            // NOLINTNEXTLINE cppcoreguidelines-pro-type-static-cast-downcast
            const auto& prog = static_cast<const ir::ProgramNode&>(node);
            for (const auto& pnode : prog.preamble()) {
                // NOLINTNEXTLINE cppcoreguidelines-pro-type-static-cast-downcast
                const auto& ec = static_cast<const ir::ExternCallNode&>(*pnode);
                *out_ << "    (void)" << ec.callee() << "(";
                bool first = true;
                for (const auto& arg : ec.args()) {
                    if (!first)
                        *out_ << ", ";
                    first = false;
                    *out_ << emit_raw_expr(arg);
                }
                *out_ << ");\n";
            }
            return emit_node(prog.main_node());
        }
    }
    // NOLINTEND cppcoreguidelines-pro-type-static-cast-downcast
    throw std::runtime_error("ibex_compile: unknown IR node kind");
}

auto Emitter::emit_filter_expr(const ir::FilterExpr& expr) -> std::string {
    return std::visit(
        [](const auto& node) -> std::string {
            using T = std::decay_t<decltype(node)>;
            if constexpr (std::is_same_v<T, ir::FilterColumn>) {
                return "ibex::ops::filter_col(\"" + escape_string(node.name) + "\")";
            } else if constexpr (std::is_same_v<T, ir::FilterLiteral>) {
                return std::visit(
                    [](const auto& v) -> std::string {
                        using V = std::decay_t<decltype(v)>;
                        if constexpr (std::is_same_v<V, std::int64_t>) {
                            return "ibex::ops::filter_int(std::int64_t{" + std::to_string(v) + "})";
                        } else if constexpr (std::is_same_v<V, double>) {
                            return "ibex::ops::filter_dbl(" + format_double(v) + ")";
                        } else if constexpr (std::is_same_v<V, bool>) {
                            return std::string("ibex::ops::filter_bool(") + (v ? "true" : "false") +
                                   ")";
                        } else if constexpr (std::is_same_v<V, std::string>) {
                            return "ibex::ops::filter_str(\"" + escape_string(v) + "\")";
                        } else if constexpr (std::is_same_v<V, Date>) {
                            return "ibex::ops::filter_date(ibex::Date{std::int32_t{" +
                                   std::to_string(v.days) + "}})";
                        } else {
                            static_assert(std::is_same_v<V, Timestamp>);
                            return "ibex::ops::filter_timestamp(ibex::Timestamp{std::int64_t{" +
                                   std::to_string(v.nanos) + "}})";
                        }
                    },
                    node.value);
            } else if constexpr (std::is_same_v<T, ir::FilterArith>) {
                return "ibex::ops::filter_arith(ibex::ir::ArithmeticOp::" + emit_arith_op(node.op) +
                       ", " + emit_filter_expr(*node.left) + ", " + emit_filter_expr(*node.right) +
                       ")";
            } else if constexpr (std::is_same_v<T, ir::FilterCmp>) {
                return "ibex::ops::filter_cmp(ibex::ir::CompareOp::" + emit_compare_op(node.op) +
                       ", " + emit_filter_expr(*node.left) + ", " + emit_filter_expr(*node.right) +
                       ")";
            } else if constexpr (std::is_same_v<T, ir::FilterAnd>) {
                return "ibex::ops::filter_and(" + emit_filter_expr(*node.left) + ", " +
                       emit_filter_expr(*node.right) + ")";
            } else if constexpr (std::is_same_v<T, ir::FilterOr>) {
                return "ibex::ops::filter_or(" + emit_filter_expr(*node.left) + ", " +
                       emit_filter_expr(*node.right) + ")";
            } else if constexpr (std::is_same_v<T, ir::FilterNot>) {
                return "ibex::ops::filter_not(" + emit_filter_expr(*node.operand) + ")";
            } else if constexpr (std::is_same_v<T, ir::FilterIsNull>) {
                return "ibex::ops::filter_is_null(" + emit_filter_expr(*node.operand) + ")";
            } else {
                static_assert(std::is_same_v<T, ir::FilterIsNotNull>);
                return "ibex::ops::filter_is_not_null(" + emit_filter_expr(*node.operand) + ")";
            }
        },
        expr.node);
}

auto Emitter::emit_expr(const ir::Expr& expr) -> std::string {
    return std::visit(
        [&](const auto& node) -> std::string {
            using T = std::decay_t<decltype(node)>;
            if constexpr (std::is_same_v<T, ir::ColumnRef>) {
                return "ibex::ops::col_ref(\"" + escape_string(node.name) + "\")";
            } else if constexpr (std::is_same_v<T, ir::Literal>) {
                return std::visit(
                    [&](const auto& v) -> std::string {
                        using V = std::decay_t<decltype(v)>;
                        if constexpr (std::is_same_v<V, std::int64_t>) {
                            return "ibex::ops::int_lit(std::int64_t{" + std::to_string(v) + "})";
                        } else if constexpr (std::is_same_v<V, double>) {
                            return "ibex::ops::dbl_lit(" + format_double(v) + ")";
                        } else if constexpr (std::is_same_v<V, bool>) {
                            return "ibex::ops::int_lit(std::int64_t{" + std::string(v ? "1" : "0") +
                                   "})";
                        } else if constexpr (std::is_same_v<V, std::string>) {
                            return "ibex::ops::str_lit(\"" + escape_string(v) + "\")";
                        } else if constexpr (std::is_same_v<V, Date>) {
                            return "ibex::ops::date_lit(ibex::Date{std::int32_t{" +
                                   std::to_string(v.days) + "}})";
                        } else {
                            static_assert(std::is_same_v<V, Timestamp>);
                            return "ibex::ops::timestamp_lit(ibex::Timestamp{std::int64_t{" +
                                   std::to_string(v.nanos) + "}})";
                        }
                    },
                    node.value);
            } else if constexpr (std::is_same_v<T, ir::BinaryExpr>) {
                return "ibex::ops::binop(ibex::ir::ArithmeticOp::" + emit_arith_op(node.op) + ", " +
                       emit_expr(*node.left) + ", " + emit_expr(*node.right) + ")";
            } else if constexpr (std::is_same_v<T, ir::CallExpr>) {
                std::string s = "ibex::ops::fn_call(\"" + escape_string(node.callee) + "\", {";
                bool first = true;
                for (const auto& arg : node.args) {
                    if (!first)
                        s += ", ";
                    first = false;
                    s += emit_expr(*arg);
                }
                s += "})";
                if (!node.named_args.empty()) {
                    s.pop_back();  // remove trailing ')'
                    s += ", {";
                    bool first_named = true;
                    for (const auto& narg : node.named_args) {
                        if (!first_named)
                            s += ", ";
                        first_named = false;
                        s += "ibex::ops::NamedArgExpr{\"" + escape_string(narg.name) + "\", " +
                             emit_expr(*narg.value) + "}";
                    }
                    s += "})";
                }
                return s;
            }
            throw std::runtime_error("ibex_compile: unknown expression type");
        },
        expr.node);
}

auto Emitter::emit_compare_op(ir::CompareOp op) -> std::string {
    switch (op) {
        case ir::CompareOp::Eq:
            return "Eq";
        case ir::CompareOp::Ne:
            return "Ne";
        case ir::CompareOp::Lt:
            return "Lt";
        case ir::CompareOp::Le:
            return "Le";
        case ir::CompareOp::Gt:
            return "Gt";
        case ir::CompareOp::Ge:
            return "Ge";
    }
    return "Eq";
}

auto Emitter::emit_arith_op(ir::ArithmeticOp op) -> std::string {
    switch (op) {
        case ir::ArithmeticOp::Add:
            return "Add";
        case ir::ArithmeticOp::Sub:
            return "Sub";
        case ir::ArithmeticOp::Mul:
            return "Mul";
        case ir::ArithmeticOp::Div:
            return "Div";
        case ir::ArithmeticOp::Mod:
            return "Mod";
    }
    return "Add";
}

auto Emitter::emit_raw_expr(const ir::Expr& expr) -> std::string {
    return std::visit(
        [&](const auto& node) -> std::string {
            using T = std::decay_t<decltype(node)>;
            if constexpr (std::is_same_v<T, ir::Literal>) {
                return std::visit(
                    [&](const auto& v) -> std::string {
                        using V = std::decay_t<decltype(v)>;
                        if constexpr (std::is_same_v<V, std::int64_t>) {
                            return std::to_string(v);
                        } else if constexpr (std::is_same_v<V, double>) {
                            return format_double(v);
                        } else if constexpr (std::is_same_v<V, bool>) {
                            return v ? "1" : "0";
                        } else if constexpr (std::is_same_v<V, std::string>) {
                            return "\"" + escape_string(v) + "\"";
                        } else if constexpr (std::is_same_v<V, Date>) {
                            return "ibex::Date{std::int32_t{" + std::to_string(v.days) + "}}";
                        } else {
                            static_assert(std::is_same_v<V, Timestamp>);
                            return "ibex::Timestamp{std::int64_t{" + std::to_string(v.nanos) + "}}";
                        }
                    },
                    node.value);
            }
            throw std::runtime_error("ibex_compile: non-literal argument in extern call");
        },
        expr.node);
}

auto Emitter::emit_agg_func(ir::AggFunc func) -> std::string {
    switch (func) {
        case ir::AggFunc::Sum:
            return "Sum";
        case ir::AggFunc::Mean:
            return "Mean";
        case ir::AggFunc::Min:
            return "Min";
        case ir::AggFunc::Max:
            return "Max";
        case ir::AggFunc::Count:
            return "Count";
        case ir::AggFunc::First:
            return "First";
        case ir::AggFunc::Last:
            return "Last";
        case ir::AggFunc::Median:
            return "Median";
        case ir::AggFunc::Stddev:
            return "Stddev";
        case ir::AggFunc::Ewma:
            return "Ewma";
        case ir::AggFunc::Quantile:
            return "Quantile";
        case ir::AggFunc::Skew:
            return "Skew";
        case ir::AggFunc::Kurtosis:
            return "Kurtosis";
    }
    return "Sum";
}

}  // namespace ibex::codegen
